version: '3.7'
services:
  database-root:
    image: mariadb:10.4
    command: --max_allowed_packet=629145600
    environment:
      # default user is "root"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306

  database-tenant:
    image: mariadb:10.4
    command: --max_allowed_packet=629145600
    environment:
      # default user is "root"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_econ
    ports:
      - 3307:3306
    volumes:
      - ./init_tenant:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4.7.6-standalone
    restart: always
    ports:
      - 8080:8080
